In [ ]:
#@title Twitter Auth Token

twitter_auth_token = 'input twitter auth token here'

In [ ]:
# Install Node.js dan dependency untuk tweet-harvest
!sudo apt-get update

# Install package dasar untuk menambahkan repository NodeSource
!sudo apt-get install -y ca-certificates curl gnupg

# Tambahkan repository Node.js 20
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

# Update setelah repository Node.js ditambahkan, lalu install Node.js dan dependency browser
!sudo apt-get update
!sudo apt-get install -y nodejs \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libcups2 \
  libdrm2 \
  libxkbcommon0 \
  libxcomposite1 \
  libxdamage1 \
  libxfixes3 \
  libxrandr2 \
  libgbm1 \
  libgtk-3-0 \
  libnss3 \
  libasound2

# Cek versi Node.js
!node -v

Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:4 https://cli.github.com/packages stable InRelease [3,917 B]
Get:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Hit:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:10 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,183 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [4,006 kB]
Get:12 https://cli.github.com/packages stable/main amd64 Packages [355 B]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,303 kB]
Get:14 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.4 MB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,357 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,489 kB]
Get:17 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,059 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,611 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [112 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [39.0 kB]
Get:21 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.6 kB]
Fetched 40.0 MB in 7s (5,687 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.24).
gnupg is already the newest version (2.2.27-3ubuntu2.5).
gnupg set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 30 not upgraded.
deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:4 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:9 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages [14.7 kB]
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 26.8 kB in 1s (22.3 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxdamage1 set to manually installed.
libxfixes3 is already the newest version (1:6.0.0-1).
libxfixes3 set to manually installed.
libxkbcommon0 is already the newest version (1.4.0-1).
libxkbcommon0 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrandr2 set to manually installed.
libasound2 is already the newest version (1.2.6.1-1ubuntu1.1).
libasound2 set to manually installed.
libdrm2 is already the newest version (2.4.113-2~ubuntu0.22.04.1).
libdrm2 set to manually installed.
libgbm1 is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libgbm1 set to manually installed.
libnss3 is already the newest version (2:3.98-0ubuntu0.22.04.3).
libnss3 set to manually installed.
The following additional packages will be installed:
  at-spi2-core gsettings-desktop-schemas libatk1.0-data libatspi2.0-0
  libgtk-3-bin libgtk-3-common librsvg2-common libxtst6 session-migration
Suggested packages:
  cups-common gvfs
The following NEW packages will be installed:
  at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0 libatk1.0-0
  libatk1.0-data libatspi2.0-0 libgtk-3-0 libgtk-3-bin libgtk-3-common
  librsvg2-common libxcomposite1 libxtst6 nodejs session-migration
The following packages will be upgraded:
  libcups2
1 upgraded, 14 newly installed, 0 to remove and 29 not upgraded.
Need to get 36.2 MB of archives.
After this operation, 209 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:8 https://deb.nodesource.com/node_20.x nodistro/main amd64 nodejs amd64 20.20.2-1nodesource1 [32.2 MB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcups2 amd64 2.4.1op1-1ubuntu4.20 [266 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-common all 3.24.33-1ubuntu2.2 [239 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-0 amd64 3.24.33-1ubuntu2.2 [3,053 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-bin amd64 3.24.33-1ubuntu2.2 [69.6 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 librsvg2-common amd64 2.52.5+dfsg-3ubuntu0.2 [17.7 kB]
Fetched 36.2 MB in 1s (60.3 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 15.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package libatspi2.0-0:amd64.
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../00-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../01-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../02-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../03-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../04-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../05-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../06-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../07-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Preparing to unpack .../08-libcups2_2.4.1op1-1ubuntu4.20_amd64.deb ...
Unpacking libcups2:amd64 (2.4.1op1-1ubuntu4.20) over (2.4.1op1-1ubuntu4.16) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../09-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package libgtk-3-common.
Preparing to unpack .../10-libgtk-3-common_3.24.33-1ubuntu2.2_all.deb ...
Unpacking libgtk-3-common (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package libgtk-3-0:amd64.
Preparing to unpack .../11-libgtk-3-0_3.24.33-1ubuntu2.2_amd64.deb ...
Unpacking libgtk-3-0:amd64 (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package libgtk-3-bin.
Preparing to unpack .../12-libgtk-3-bin_3.24.33-1ubuntu2.2_amd64.deb ...
Unpacking libgtk-3-bin (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package librsvg2-common:amd64.
Preparing to unpack .../13-librsvg2-common_2.52.5+dfsg-3ubuntu0.2_amd64.deb ...
Unpacking librsvg2-common:amd64 (2.52.5+dfsg-3ubuntu0.2) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../14-nodejs_20.20.2-1nodesource1_amd64.deb ...
Unpacking nodejs (20.20.2-1nodesource1) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up nodejs (20.20.2-1nodesource1) ...
Setting up librsvg2-common:amd64 (2.52.5+dfsg-3ubuntu0.2) ...
Setting up libcups2:amd64 (2.4.1op1-1ubuntu4.20) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up libgtk-3-common (3.24.33-1ubuntu2.2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libgdk-pixbuf-2.0-0:amd64 (2.42.8+dfsg-1ubuntu0.5) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.9) ...
Setting up libgtk-3-0:amd64 (3.24.33-1ubuntu2.2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

Setting up libgtk-3-bin (3.24.33-1ubuntu2.2) ...
Setting up at-spi2-core (2.44.0-3) ...
v20.20.2

In [ ]:
# Crawl Data

filename = 'Keracunan_mbg_2.csv'
search_keyword = 'keracunan makan bergizi gratis'
limit = 3000

!npx --yes tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦npm warn deprecated glob@7.2.3: Old versions of glob are not supported, and contain widely publicized security vulnerabilities, which have been fixed in the current version. Please update. Support for old versions may be purchased (at exorbitant rates) by contacting i@izs.me
⠦npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
⠧npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Filling in keywords: keracunan makan bergizi gratis


-- Scrolling... (1) (2) (3)Created new directory: /content/tweets-data


Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 20

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 40

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 60

-- Scrolling... (1) (2) (3) (4)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 80

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 100

-- Scrolling... (1) (2) (3) (4)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 120

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 140

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 160

-- Scrolling... (1) (2) (3) (4) (5) (6)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 180

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 200

-- Scrolling... (1) (2) (3) (4)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 220

-- Scrolling... (1) (2) (3) (4) (5)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 240

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 260

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 280

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 300

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 320

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 340

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 360

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 380

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 400

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 420

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 440

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 460

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 480

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 500

-- Scrolling... (1) (2) (3) (4)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 520

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 540

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 560

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 580

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 600

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 620

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 640

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 660

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 680

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 700

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 715

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 717

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/Keracunan_mbg_2.csv
Total tweets saved: 719
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@88c5b04540c79a652c68374042025b16"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@52cdadb51d2700395822b5091150ce57"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@c9e4a5143e3463a1c7cbc1bf216a506d"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2)[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@f3b46f69cd7d157cd3a98d43839171c2"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 719 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/{filename}"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df)

# Check the length of the DataFrame
num_rows = len(df)
print(f"The number of rows in the DataFrame is: {num_rows}")

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1974063382677594125,Fri Oct 03 10:46:01 +0000 2025,136,Badan Gizi Nasional (BGN) mengungkapkan inside...,1974063382677594125,https://pbs.twimg.com/media/G2VILfdbMAMSCVk.jpg,NaN,in,NaN,141,362,40,https://x.com/undefined/status/197406338267759...,23343960,NaN
1,2048568169401577814,Mon Apr 27 01:01:26 +0000 2026,8349,Balita berumur 2 th meninggal dunia setelah me...,2048568169401577814,https://pbs.twimg.com/ext_tw_video_thumb/20485...,NaN,in,NaN,149,209,4457,https://x.com/undefined/status/204856816940157...,1100609875,NaN
2,2065660433974063442,Sat Jun 13 05:00:00 +0000 2026,57,Anggota Komisi XIII DPR RI Fraksi PDI Perjuang...,2065660433974063442,https://pbs.twimg.com/amplify_video_thumb/2065...,NaN,in,NaN,3,9,26,https://x.com/undefined/status/206566043397406...,153407983,NaN
3,1970806096026857517,Wed Sep 24 11:02:43 +0000 2025,790,Situasi Kantor Kecamatan Cipongkor Kabupaten B...,1970806096026857517,https://pbs.twimg.com/ext_tw_video_thumb/19708...,NaN,in,NaN,29,72,394,https://x.com/undefined/status/197080609602685...,785145642,NaN
4,1918330640443031908,Fri May 02 15:44:00 +0000 2025,33,MAKAN BERGIZI GRATIS KERACUNAN. Dalam sembilan...,1918330640443031908,https://pbs.twimg.com/ext_tw_video_thumb/19183...,NaN,in,NaN,0,4,18,https://x.com/undefined/status/191833064044303...,1040306964100669440,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,2063819115241128208,Mon Jun 08 03:03:15 +0000 2026,4,Bahan pangan lokal dari hasil kebun mama-mama ...,2063819115241128208,https://pbs.twimg.com/amplify_video_thumb/2063...,NaN,in,NaN,0,0,0,https://x.com/undefined/status/206381911524112...,2049006428799791104,NaN
715,2065782317856247976,Sat Jun 13 16:12:40 +0000 2026,0,@dosenkesmas bahkan nasi ada glukosa pisang ad...,2065829716893061257,NaN,dosenkesmas,in,NaN,0,0,0,https://x.com/undefined/status/206582971689306...,132062416,NaN
716,2065833899394322539,Sat Jun 13 16:29:17 +0000 2026,0,Viral Ratusan Minyak Goreng Kemasan Mengapung ...,2065833899394322539,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/206583389939432...,1541606354179465216,NaN
717,2065837348504719412,Sat Jun 13 16:42:59 +0000 2026,0,Sungguh sangat disayangkan kalau anggaran maka...,2065837348504719412,https://pbs.twimg.com/media/HKtTuJZa8AA7Ueu.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/206583734850471...,1496351386300477443,NaN
718,2065837271065239950,Sat Jun 13 16:42:41 +0000 2026,0,Yang kemarin suka makan gorengan sekarang gak ...,2065837271065239950,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/206583727106523...,251410137,NaN

The number of rows in the DataFrame is: 719

In [1]:
import pandas as pd

# Load dataset
df = pd.read_csv("Keracunan_mbg_2.csv")

# Lihat nama kolom
print(df.columns)

# Filter tweet dengan minimal 50 komentar
df_filtered = df[df['reply_count'] >= 50]

# Jumlah data setelah filter
print(f"Jumlah tweet setelah filter: {len(df_filtered)}")

# Simpan hasil
df_filtered.to_csv("Keracunan_mbg_min_reply_50.csv", index=False)

# Tampilkan beberapa data
df_filtered.head()

Index(['conversation_id_str', 'created_at', 'favorite_count', 'full_text',
       'id_str', 'image_url', 'in_reply_to_screen_name', 'lang', 'location',
       'quote_count', 'reply_count', 'retweet_count', 'tweet_url',
       'user_id_str', 'username'],
      dtype='object')
Jumlah tweet setelah filter: 54

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1974063382677594125,Fri Oct 03 10:46:01 +0000 2025,136,Badan Gizi Nasional (BGN) mengungkapkan inside...,1974063382677594125,https://pbs.twimg.com/media/G2VILfdbMAMSCVk.jpg,NaN,in,NaN,141,362,40,https://x.com/undefined/status/197406338267759...,23343960,NaN
1,2048568169401577814,Mon Apr 27 01:01:26 +0000 2026,8349,Balita berumur 2 th meninggal dunia setelah me...,2048568169401577814,https://pbs.twimg.com/ext_tw_video_thumb/20485...,NaN,in,NaN,149,209,4457,https://x.com/undefined/status/204856816940157...,1100609875,NaN
3,1970806096026857517,Wed Sep 24 11:02:43 +0000 2025,790,Situasi Kantor Kecamatan Cipongkor Kabupaten B...,1970806096026857517,https://pbs.twimg.com/ext_tw_video_thumb/19708...,NaN,in,NaN,29,72,394,https://x.com/undefined/status/197080609602685...,785145642,NaN
18,1894185220225823202,Tue Feb 25 00:38:43 +0000 2025,250,80 Tahun Indonesia Merdeka Tapi Kenapa Malah A...,1894185220225823202,https://pbs.twimg.com/media/Gkl_a3tasAArEIl.jpg,NaN,in,NaN,7,108,60,https://x.com/undefined/status/189418522022582...,1826886526657318912,NaN
21,1921127168244908541,Sat May 10 08:56:24 +0000 2025,368,171 Siswa di Bogor Diduga Keracunan Usai Konsu...,1921127168244908541,https://pbs.twimg.com/ext_tw_video_thumb/19211...,NaN,in,NaN,15,56,149,https://x.com/undefined/status/192112716824490...,1334853481019056128,NaN